# Generated by Django 6.1.1 on 2026-09-30 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('chair', models.CharField(max_length=255, verbose_name='chair')),
            ],
        ),
        migrations.CreateModel(
            name='MainPageInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Факультет X', max_length=150, verbose_name='faculty_name')),
                ('description', models.TextField(verbose_name='description')),
                ('general_info', models.TextField(verbose_name='general_info')),
                ('contacts', models.TextField(verbose_name='contacts')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('code', models.CharField(max_length=25, verbose_name='code')),
                ('description', models.TextField(max_length=1000, verbose_name='description')),
                ('coordinator', models.CharField(max_length=150, verbose_name='coordinator')),
                ('coord_number', models.CharField(max_length=10, verbose_name='coord_number')),
                ('courses', models.TextField(max_length=1000, verbose_name='courses')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='faculty_app.department', verbose_name='department')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('position', models.CharField(max_length=150, verbose_name='position')),
                ('degree', models.CharField(max_length=150, verbose_name='degree')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='faculty_app.department', verbose_name='department')),
            ],
        ),
    ]
