# Generated by Django 6.1.1 on 2026-10-05 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=255, verbose_name='Університет', null=True)),
                ('languages', models.CharField(max_length=255, verbose_name='Мови навчання')),
                ('places', models.CharField(max_length=50, verbose_name='Кількість місць', null=True)),
                ('deadline', models.DateField(verbose_name='Дедлайн подачі')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
            ],
        ),
    ]
