# Generated by Django 6.1.1 on 2026-10-05 19:10

from django.db import migrations

FORWARD_SQL = """
INSERT INTO faculty_app_exchangeprogram (university, languages, places, deadline, description) VALUES
('Uniwersytet Warszawski, Польща', 'польська, англійська', '5', '2026-11-15', 'Провідний університет Польщі з багатовіковою історією. Пропонує широкий вибір гуманітарних дисциплін.'),
('KU Leuven (Бельгія)', 'English', '2 місця', '2026-12-01', 'Один із найстаріших і найпрестижніших університетів Європи. Відомий своїми інноваційними дослідницькими центрами.'),
('Vilnius University, Литва', 'англійська', 'до 4', '2026-10-20', 'Найбільший університет Литви. Відкриває двері до глибокого вивчення балтійського регіону.'),
('Uniwersytet Jagielloński, Польща', 'Польська, Англійська', '3', '2026-11-15', 'Розташований у Кракові, цей заклад славиться сильною юридичною та історичною школами.'),
('University of Tartu - Естонія', 'англійська, естонська', '2', '2027-01-10', 'Національний університет Естонії. Визнаний європейський лідер у галузі інформаційних технологій та біомедицини.'),
('Masaryk University, Чехія', 'англійська', '1 місце', '2026-09-30', 'Другий за величиною університет Чехії. Має надсучасні кампуси та лабораторії.');
"""

REVERSE_SQL = """
DELETE FROM faculty_app_exchangeprogram;
"""


class Migration(migrations.Migration):
    dependencies = [
        ('faculty_app', '0002_exchangeprogram'),
    ]

    operations = [
        migrations.RunSQL(FORWARD_SQL, reverse_sql=REVERSE_SQL)
    ]
