# Generated by Django 6.1.1 on 2026-10-05 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_app', '0003_auto_20261005_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeprogram',
            name='country',
            field=models.CharField(max_length=255, null=True, verbose_name='Країна'),
        ),
        migrations.AddField(
            model_name='exchangeprogram',
            name='university_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Назва університету'),
        ),
    ]
