# Generated by Django 6.1.1 on 2026-10-05 20:11

from django.db import migrations


def split_university_data(apps, schema_editor):
    ExchangeProgram = apps.get_model('faculty_app', 'ExchangeProgram')

    for program in ExchangeProgram.objects.all():
        raw_text = program.university
        if '(' in raw_text:
            name, country = raw_text.split('(')
            country = country.replace(')', '')
        elif '-' in raw_text:
            name, country = raw_text.split('-')
        elif ',' in raw_text:
            name, country = raw_text.split(',')
        else:
            name, country = raw_text, "Невідомо"

        program.university_name = name.strip()
        program.country = country.strip()
        program.save()


def merge_university_data(apps, schema_editor):
    ExchangeProgram = apps.get_model('faculty_app', 'ExchangeProgram')

    for program in ExchangeProgram.objects.all():
        if program.university_name and program.country:
            program.university = f"{program.university_name}, {program.country}"
            program.save()


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_app', '0004_exchangeprogram_country_and_more'),
    ]

    operations = [
        migrations.RunPython(split_university_data, reverse_code=merge_university_data)
    ]
