# Generated by Django 6.1.1 on 2026-10-05 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_app', '0005_auto_20261005_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangeprogram',
            name='university',
        ),
        migrations.AlterField(
            model_name='exchangeprogram',
            name='country',
            field=models.CharField(max_length=255, verbose_name='Країна'),
        ),
        migrations.AlterField(
            model_name='exchangeprogram',
            name='university_name',
            field=models.CharField(max_length=255, verbose_name='Назва університету'),
        ),
    ]
