# Generated by Django 6.1.1 on 2026-10-05 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_app', '0006_remove_exchangeprogram_university_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeprogram',
            name='places_count',
            field=models.IntegerField(default=0, verbose_name='Місця'),
            preserve_default=False,
        ),
    ]
