# Generated by Django 6.1.1 on 2026-10-05 20:23

import re
from django.db import migrations


def extract_places(apps, schema_editor):
    ExchangeProgram = apps.get_model('faculty_app', 'ExchangeProgram')

    for program in ExchangeProgram.objects.all():
        raw_text = program.places
        # Шукаємо всі цифри в рядку
        numbers = re.findall(r'\d+', raw_text)

        if numbers:
            program.places_count = int(numbers[0])
        else:
            program.places_count = 0

        program.save()


def reverse_extract_places(apps, schema_editor):
    ExchangeProgram = apps.get_model('faculty_app', 'ExchangeProgram')

    for program in ExchangeProgram.objects.all():
        program.places = str(program.places_count)
        program.save()


class Migration(migrations.Migration):
    dependencies = [
        ('faculty_app', '0007_exchangeprogram_places_count'),
    ]

    operations = [
        migrations.RunPython(extract_places, reverse_code=reverse_extract_places)
    ]
