# Generated by Django 6.1.1 on 2026-10-05 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_app', '0008_auto_20261005_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangeprogram',
            name='places',
        ),
        migrations.AlterField(
            model_name='exchangeprogram',
            name='places_count',
            field=models.IntegerField(verbose_name='Кількість місць'),
        ),
    ]
