# Generated by Django 6.1.1 on 2026-10-05 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_app', '0009_remove_exchangeprogram_places_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchangeprogram',
            old_name='places_count',
            new_name='places',
        ),
    ]
